Resolve Toolbar Icon Excessive Shrinkage - I228
accordproject/web-components pull request #229
Opened 2020-12-20 09:31 UTC by K-Kumar-01

# Closes #228  <CORRESPONDING ISSUE NUMBER>

The toolbar icons in markdown shrank too much. Resolved that issue.

### Changes

- <ONE> Changed the stylings of toolbar icons
- <TWO> Used media queries to achieve this.

### Flags

- <ONE> The separator has a `height:50px` that may seem a bit large in some small area range.
- <TWO> Devices less than 330px will have an overflow of the toolbar.

### Screenshots or Video

![DeepinScreenshot_20201220144521](https://user-images.githubusercontent.com/59891164/102709838-0176e080-42d4-11eb-8272-72b7e085a065.png)
![DeepinScreenshot_20201220144528](https://user-images.githubusercontent.com/59891164/102709839-03d93a80-42d4-11eb-8bfb-b128efcc07cb.png)
![DeepinScreenshot_20201220144537](https://user-images.githubusercontent.com/59891164/102709840-050a6780-42d4-11eb-9c8d-9594d404d778.png)
![DeepinScreenshot_20201220144544](https://user-images.githubusercontent.com/59891164/102709842-05a2fe00-42d4-11eb-91bc-d5c50c7c829c.png)
![DeepinScreenshot_20201220144610](https://user-images.githubusercontent.com/59891164/102709844-06d42b00-42d4-11eb-9d1e-31db56a88d38.png)

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

2020-12-21 13:34 UTC, irmerk commented
We should have addressed this in #228, but any thoughts on how this should _ideally_ be @Michael-Grover? My first thought is having a minimum width for the whole editor, so the icons can not need to resize or anything.

2020-12-21 13:49 UTC, K-Kumar-01 commented
> We should have addressed this in #228, but any thoughts on how this should _ideally_ be @Michael-Grover? My first thought is having a minimum width for the whole editor, so the icons can not need to resize or anything.

@irmerk 
The icons will shrink when the window is resized so I don't think this will be a good approach.
I don't have any other idea about how this should be tackled though

2020-12-21 15:31 UTC, Michael-Grover commented
@irmerk I agree that a minimum width for the editor would make sense. @K-Kumar-01 How about making the minimum the same width as the contract editor component? It looks like that's 670px.

2020-12-21 15:46 UTC, K-Kumar-01 commented
> @irmerk I agree that a minimum width for the editor would make sense. @K-Kumar-01 How about making the minimum the same width as the contract editor component? It looks like that's 670px.

@Michael-Grover  
I cannot understand what to do. Can you explain please as I am confused about what to do? :sweat_smile:

2020-12-21 17:04 UTC, Michael-Grover commented
@K-Kumar-01 I'm not sure what the best way to do this is from a coding perspective, but what I'm suggesting is that we:

Make this sure this component can't reduce to a width smaller than 670px. When the screen is too narrow to accommodate the 670px width component, the component will overflow off the right side of the screen. For example, if the viewport is 400px width, the component will be 670px width, however if the viewport is 1200px width, the component will grow in size to fit the screen like it currently does. This will ensure the toolbar is never so narrow that the icons shrink.

![image](https://user-images.githubusercontent.com/40569793/102801924-e82d6d00-4383-11eb-8c6b-3c19c50cc944.png)

2020-12-21 20:00 UTC, K-Kumar-01 commented
> @K-Kumar-01 I'm not sure what the best way to do this is from a coding perspective, but what I'm suggesting is that we:
> 
> Make this sure this component can't reduce to a width smaller than 670px. When the screen is too narrow to accommodate the 670px width component, the component will overflow off the right side of the screen. For example, if the viewport is 400px width, the component will be 670px width, however if the viewport is 1200px width, the component will grow in size to fit the screen like it currently does. This will ensure the toolbar is never so narrow that the icons shrink.
> 
> ![image](https://user-images.githubusercontent.com/40569793/102801924-e82d6d00-4383-11eb-8c6b-3c19c50cc944.png)

@Michael-Grover 
Well, thanks for the explanation. I had a few doubts and queries. On mobile screens wouldn't it be uncomfortable? Besides, I think that it may cause some styling problems though I am not sure about it.
I would like to draw attention to one more thing that `670px +210px` i.e. a total of `880px` or greater would be required for the working when the sidebar is shown.
So I am not fully confident about this approach.
Would like suggestions from @irmerk also on how can we go.

2020-12-21 22:21 UTC, irmerk commented
I don't think we should be concerned with mobile usage. This repository is not geared towards that end. In the future, we can approach mobile functionality.

In the meantime, I think we should set a minimum width for the editor and toolbar and let if overflow if the page width is reduced to less than that. This should remove the issue of icons resizing because nothing can go lower in width than what we specify.

2020-12-22 11:58 UTC, K-Kumar-01 commented
> I don't think we should be concerned with mobile usage. This repository is not geared towards that end. In the future, we can approach mobile functionality.
> 
> In the meantime, I think we should set a minimum width for the editor and toolbar and let if overflow if the page width is reduced to less than that. This should remove the issue of icons resizing because nothing can go lower in width than what we specify.

@irmerk @Michael-Grover 
I have tried implementing the above.
## Attaching screenshots for reference.
![DeepinScreenshot_20201222172038](https://user-images.githubusercontent.com/59891164/102886029-5c4a3c80-447a-11eb-8379-e8fb81939ce2.png)
![DeepinScreenshot_20201222172105](https://user-images.githubusercontent.com/59891164/102886036-5eac9680-447a-11eb-95a6-6fef29adafc2.png)

If it is suitable, I will commit it otherwise make any more changes needed.
I used js for styling as the styles applied were to the `body` tag and a `slate` component which I could not figure out to apply.
The styles though will be applied only here using `useEffect`.
## Code
```
useEffect(()=>{
    const toolbar = document.getElementById("ap-rich-text-editor-toolbar");
    toolbar.parentElement.style.minWidth = "630px";
    document.body.style.overflowX = "auto";
  },[])
```
Let me know if there are any changes required.

2020-12-22 13:43 UTC, Michael-Grover commented
Hi @K-Kumar-01 , I opened the Netlify link and I'm somehow still able to reduce the width of the component below the minimum we set. @irmerk are you seeing the same behavior? 

![image](https://user-images.githubusercontent.com/40569793/102894813-abb84a80-4431-11eb-8943-7795741695e4.png)

2020-12-22 14:05 UTC, irmerk commented
@K-Kumar-01 could you add your commits to the PR so we can view the changes?

2020-12-22 15:14 UTC, K-Kumar-01 commented
@irmerk  @Michael-Grover 
I have added my latest commits to the PR.
Let me know if there are any changes required.
I apologize for the earlier incident @Michael-Grover. I forgot to push the commits :sweat_smile:

2020-12-22 18:39 UTC, Michael-Grover approved these changes
looks good to me. @irmerk may want to review as well.

2020-12-22 19:20 UTC, irmerk requested changes
I don't think this is the right approach. I. think the consumer of the `ui-markdown-editor` component should determine the overflow. In this instance that would be the Storybook. Also, you've already set the `min-width` on the `Menu`, so this `useEffect` isn't necessary.

2020-12-22 19:44 UTC, K-Kumar-01 commented
@irmerk 
>I. think the consumer of the ui-markdown-editor component should determine the overflow. In this instance that would be the Storybook.

I am not quite getting what you are trying to say. :sweat_smile:
Could you please tell me about this?

As for the useEffect part, the minWidth only makes the toolbar to a min-width.
The area that will contain the text (where the slate tag is used) won't be shrinked. So I had to resort to useEffect for that part

2020-12-23 20:08 UTC, K-Kumar-01 commented
> @irmerk
> 
> > I. think the consumer of the ui-markdown-editor component should determine the overflow. In this instance that would be the Storybook.
> 
> I am not quite getting what you are trying to say. 
> Could you please tell me about this?
> 
> As for the useEffect part, the minWidth only makes the toolbar to a min-width.
> The area that will contain the text (where the slate tag is used) won't be shrinked. So I had to resort to useEffect for that part

@irmerk 
Any updates on this one?

2021-01-05 14:03 UTC, irmerk commented
Yes the `ui-markdown-editor` is a component, which is used in the Storybook and `ui-contract-editor`, or any other app that decides to use it. Those components are the ones that should decide the overflow of `ui-markdown-editor` when they render it.

2021-01-11 13:50 UTC, K-Kumar-01 commented
> Yes the `ui-markdown-editor` is a component, which is used in the Storybook and `ui-contract-editor`, or any other app that decides to use it. Those components are the ones that should decide the overflow of `ui-markdown-editor` when they render it.

@irmerk 
So basically the component which is currently active i.e. `ui-markdown-editor` or `ui-contract-editor` should be responsible for the 
resize?
Am I correct here?

2021-01-12 14:26 UTC, irmerk commented
Yes I believe that is correct.

2021-01-22 14:14 UTC, K-Kumar-01 commented
> Yes I believe that is correct.

@irmerk @Michael-Grover 
I have changed the approach as suggested by @irmerk .
There are global body styles added for the storybook to see overflow and div added only for markdown editor.
Let me know if there are any changes required :)

2021-01-22 18:20 UTC, Michael-Grover approved these changes
This looks good to me, thanks!

2021-01-22 19:41 UTC, irmerk commented
This still doesn't look like the right approach to me - wrapping the editor in a div with a `min-width`. I'll look into this more when I have a chance.

2021-01-22 20:08 UTC, irmerk requested changes
Sorry I haven't had much time to look into this more before and haven't been able to give very helpful guidance. I didn't look at this well enough and that resulted in [this idea](https://github.com/accordproject/web-components/pull/229#pullrequestreview-557312680).

But I believe all we really need is to configure `min-width: 600px` in these two places. We don't need `overflow-x: auto` or anything else.

2021-01-22 20:08 UTC, irmerk commented on packages/ui-markdown-editor/src/index.js
> +          && <FormatBar
Add into `packages/ui-markdown-editor/src/FormattingToolbar/ToolbarMenu.js`

2021-01-22 20:08 UTC, irmerk commented on packages/ui-markdown-editor/src/index.js
> +          }}
Add here

2021-01-22 22:04 UTC, K-Kumar-01 commented
> Sorry I haven't had much time to look into this more before and haven't been able to give very helpful guidance. I didn't look at this well enough and that resulted in [this idea](https://github.com/accordproject/web-components/pull/229#pullrequestreview-557312680).
> 
> But I believe all we really need is to configure `min-width: 600px` in these two places. We don't need `overflow-x: auto` or anything else.

@irmerk 
If `overflow-x:auto` is not set then on resizing window below a certain size the content gets cut off in my implementations. I will try to implement the suggested changes but I think that `overflow-x:auto` would be required. Will confirm and tell you after the implementation.

2021-01-22 22:26 UTC, irmerk commented
Ah, well that should be added in the storybook, not on `ui-markdown-editor`

2021-01-24 19:25 UTC, K-Kumar-01 commented
@irmerk and @Michael-Grover 
I have made some changes to the PR.
Basically providing min-width to toolbar menu and text editor separately.
Let me know if there are any changes required.

2021-01-25 13:34 UTC, irmerk approved these changes
Great, thanks for your patience! Want to get @DianaLease's 👀  on this as well.

2021-01-25 13:58 UTC, DianaLease approved these changes

2021-01-25 14:00 UTC, merged