fix(ui-markdown-editor): linebreak - #263, #267, #269
accordproject/web-components pull request #270
Opened 2021-02-26 17:23 UTC by d-e-v-esh

# Closes #263 #267 #269 

What is happening till now:

Every time we press Enter, a heading break is going to get inserted.

How it was implemented was:
1. We created a boolean which tells us if the current block is a heading.
2. We created a restriction on the `enter` keyword when being pressed from a non-heading block. This was causing #263 
3. If enter is called from a `headingblock` then we will go to our custom hotkeyActions and create a heading break
4. But if the `enter` is called from a non - heading block then we will skip our custom hotkeyActions and a default enter linebreak will occur

### Changes

1. Converted `headingbreak` to linebreak
2. This converts every single enter press to a simple linebreak and if enter is pressed from a heading block, only then we will make it a `headingbreak`
3. This removes the restriction on the enter key in the paragraph so the page break works.

### Related Issues
- Issue  #263 #267 #269 
- Pull Request #220 

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [x] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

2021-03-01 17:11 UTC, irmerk requested changes
We'll need to do a thorough investigation on all of this to see what is going on, the limitations, and what these changes do.

2021-03-01 17:47 UTC, d-e-v-esh commented
@irmerk That is great. Will that take very long?

2021-03-01 18:14 UTC, dselman requested changes

2021-03-01 18:14 UTC, dselman commented on packages/ui-markdown-editor/src/components/index.js
> +    // console.log(customElements)
Remove please.

2021-03-01 18:14 UTC, dselman commented on packages/ui-markdown-editor/src/index.js
> +
Remove please

2021-03-01 18:14 UTC, dselman commented on packages/ui-markdown-editor/src/index.js
> +        // if linebreak happens form a heading block then we run the insertHeadingBrake function
Typo in xxxBrake

2021-03-01 18:14 UTC, dselman commented on packages/ui-markdown-editor/src/index.js
> +          hotkeyActions['headingbreak']()
Use the 'headingbreak' constant please.

2021-03-01 18:14 UTC, dselman commented on packages/ui-markdown-editor/src/utilities/toolbarHelpers.js
> +  console.log(format)
Remove please.

2021-03-01 18:14 UTC, dselman commented on packages/ui-markdown-editor/src/utilities/toolbarHelpers.js
>    const br = { type, children: [text], data: {} };
Why take `type` as an argument if this is just for soft break?

2021-03-04 16:43 UTC, irmerk commented
> @irmerk That is great. Will that take very long? Should I write the description of changes and limitations in more detail?

Yeah I think so. This is a sensitive change, so as much helpful context would be great.

2021-03-05 15:21 UTC, d-e-v-esh commented
@dselman @irmerk I have updated the pull-request body and added more context highlighting the problem. Does this bring more clarity?

2021-03-08 11:27 UTC, dselman commented
When I test this using the Netlify preview there's something strange happening with the selection. Try selecting multiple paragraphs forwards, or backwards, and you see that the selection is getting extended outside of the selection target.

2021-03-09 02:15 UTC, d-e-v-esh commented
@dselman I don't see that behavior. Can you make a screen recording to show exactly what is strange?

2021-03-09 09:08 UTC, K-Kumar-01 commented
@d-e-v-esh 
https://www.loom.com/share/56a2f8833f9f481e96dd5582fce0b745
I think @dselman may be talking about this thing.

2021-03-09 10:07 UTC, dselman commented
> @dselman I don't see that behavior. Can you make a screen recording to show exactly what is strange?

It seems to be specific to Safari - I don't see it on Chrome.

2021-03-09 16:01 UTC, d-e-v-esh commented
@K-Kumar-01 Is this happening only on this update or is this on the master branch? You cut out the URL.

2021-03-09 17:44 UTC, K-Kumar-01 commented
> @K-Kumar-01 Is this happening only on this update or is this on the master branch? You cut out the URL.

@d-e-v-esh 
It is happening in the deployment of this PR only.
I have rechecked it. 
I clicked on the deploy preview and then made the above video.

2021-03-10 04:59 UTC, d-e-v-esh commented
@K-Kumar-01 That is actually a really bad bug. I'll see what is causing the problem and update.

2021-03-16 12:48 UTC, irmerk requested changes
We still haven't found time yet, but this needs investigation by @accordproject/maintainers-ui.

In the meantime @d-e-v-esh you could rebase all your commits to clean them up and put DCO signoffs on them.

2021-03-17 11:13 UTC, d-e-v-esh commented
@irmerk Does this look good now?

2021-03-17 11:50 UTC, irmerk commented
Yes looks good. I think wait to rebase again (because there are conflicting files after I merged a couple other PRs) until we review.

2021-04-01 15:17 UTC, irmerk commented
I've finally been able to look more into this. This is really thorough and I think is on the right track. Some residual awkward behavior I'm seeing is when you press <kbd>ENTER</kbd> at the end of "**My Heading**" at the top of the [demo](https://deploy-preview-270--ap-web-components.netlify.app/?path=/story/markdown-editor--demo), it inserts two new paragraphs, both of which are not headings, and places the cursor at the beginning of the second one. Could this be because we are inserting `lineBreakNode` in `insertLineBreak`?

2021-04-01 16:05 UTC, irmerk commented on packages/ui-markdown-editor/src/utilities/toolbarHelpers.js
> +  Transforms.move(editor, { distance: 1, unit: 'character' })
I ran this locally and actually I think it could be this line that we may want to back out.

2021-04-01 16:10 UTC, irmerk commented
As of right now #263 and #269 are solved for sure. I _believe_ #267 is resolved, will want extra eyes on this from @dselman and/or @jeromesimeon.

2021-04-02 16:40 UTC, d-e-v-esh commented
@irmerk Oh yes, I remember that being very annoying. I don't know why I kept it, probably because it was there from the beginning. And we were talking about implementing [this](https://github.com/accordproject/web-components/issues/260#issuecomment-790687176) after the linebreak issue is resolved. It is fixed now.

2021-04-02 18:45 UTC, irmerk commented
Great! It looks like there are still merge conflicts, so you'll want to rebase to resolve those.

2021-04-03 06:42 UTC, d-e-v-esh commented
@irmerk I am not sure if this worked. Did the conflicts go away? I can't see them.

2021-04-06 13:08 UTC, irmerk commented
Suspicious, I refreshed and it said the conflicts were there, refreshed again and they were gone.

2021-04-06 13:13 UTC, irmerk commented
There are still two issues with headings:

1. Place cursor at beginning of "My Heading"
Press <kbd>ENTER</kbd>
See that new normal line is created before and cursor is placed above "My Heading"
2. Place cursor in the middle of "My Heading"
Press <kbd>ENTER</kbd>
See that new normal line is created in between "My Heading" where cursor was placed.

2021-04-06 13:41 UTC, irmerk commented
Note: I'm looking at your code locally to see if I can see the solution.

2021-04-06 13:49 UTC, d-e-v-esh commented
@irmerk  I think we can create a new and fully working headingBreak with all the bugs fixed under the PR of #260 after this is merged. I think that would be better, isn't it?

2021-04-06 13:59 UTC, irmerk approved these changes

2021-04-06 14:10 UTC, irmerk commented
@d-e-v-esh we're going to put the changes in this PR on the working group call tomorrow to try to make sure it doesn’t lead to further confusion around linebreaks/softbreaks. If you’ll be on during the call, feel free to add to the conversation. If not, I think @dselman and I can present what the changes will do.

2021-04-06 21:01 UTC, dselman requested changes
This looks very clean - however when I try the Netlify preview and I forward-select past a line break something strange happens with the selection (whole blocks get selected). I can't reproduce the same issue with the master: https://ap-web-components.netlify.app/?path=/story/markdown-editor--demo

2021-04-07 10:27 UTC, d-e-v-esh commented
@dselman I think the reason for that seems to be [this](https://github.com/accordproject/web-components/pull/270#issuecomment-794986866) that I talked about earlier. It seems like something changed in the conversion. That behavior is not present in the master and it was also not present when I made the PR. Do you know where it could be coming from?

2021-04-07 14:52 UTC, dselman commented
> @dselman I think the reason for that seems to be [this](https://github.com/accordproject/web-components/pull/270#issuecomment-794986866) that I talked about earlier. It seems like something changed in the conversion. That behavior is not present in the master and it was also not present when I made the PR. Do you know where it could be coming from?

Sorry, no idea. Can you reproduce the issue when you run locally using this branch?

2021-04-07 17:43 UTC, d-e-v-esh commented
@dselman Yes I can. It doesn't go back to when this was not happening.

2021-04-09 14:46 UTC, irmerk commented
Update: This PR should no longer address #267

2021-04-09 14:51 UTC, irmerk commented
Also, this should unblock #260 and #284

2021-04-14 12:23 UTC, d-e-v-esh commented
@irmerk I have implemented the new `paragraphBreak` and also fixed the error that @dselman pointed out. I think it should be perfect now. Now we just need to update the demo text on the editor.

2021-04-14 13:15 UTC, irmerk approved these changes
Yes, this looks good to me! Will want @dselman on this as well.

2021-05-05 15:49 UTC, irmerk commented
Pinging @dselman on this again.

2021-05-18 13:39 UTC, dselman commented
@d-e-v-esh looks great. Can you please resolve the merge conflicts and then I will merge.

2021-05-18 13:45 UTC, dselman requested changes
Looks great. Please resolve the merge conflicts and I will merge.

2021-06-03 10:01 UTC, dselman commented
Would love to get this into the next release (this week). @d-e-v-esh will you have time to resolve the merge conflicts?

2021-10-31 15:24 UTC, d-e-v-esh commented
@dselman I removed all the merge conflicts and it works totally great. You can check it out.

2021-12-01 21:44 UTC, Michael-Grover approved these changes
lgtm, thanks!

2026-05-09 19:14 UTC, closed without merging