feat(storybook): cypress setup for the project
accordproject/web-components pull request #282
Opened 2021-03-05 11:05 UTC by sanketshevkar

Signed-off-by: User <shevkar.sanket@gmail.com>

### Changes

- Added cypress as a devDependency and wrote a dummy test within the cypress/intergrations folder.
- You need to install cypress on your local machine so as to run tests. Instructions for installing cypress on local machine: https://docs.cypress.io/guides/getting-started/installing-cypress.html#System-requirements
- To run the test you need two terminal windows, on the first one you need to run `npm run storybook` and once the storybook loads, on the second terminal within packages/storybook run `npm run cypress:open`. Cypress app would start and select the markdownEditor.spec.js file and then the test should start.

### Flags

- You might have to run `lerna clean && lerna bootstrap && lerna run build` as a new devDependency is added.

### Screenshots or Video

https://www.loom.com/share/72e05a6e0c014ba6940fb36b757580a8

### Related Issues
- Issue #14 

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

2021-03-10 20:50 UTC, irmerk commented
@mttrbrts and I are looking into this from https://github.com/accordproject/web-components/issues/279

2021-03-10 22:07 UTC, Cronus1007 requested changes

2021-03-10 22:14 UTC, Cronus1007 commented on packages/storybook/package.json
> +    "cypress:open": "cypress open"
@sanketshevkar The script name should rather reflect the work associated with the script so would be better to change the name to `test:cypress` or `test:e2e`.

2021-03-11 06:34 UTC, sanketshevkar commented
> @mttrbrts and I are looking into this from #279

Okay cool. Should I close this pr?

2021-03-12 13:13 UTC, mttrbrts commented
> > @mttrbrts and I are looking into this from #279
> 
> Okay cool. Should I close this pr?

No, I've added another commit which completes the basic setup. @rkotangoor @irmerk  can you review, please?

2021-03-12 13:17 UTC, mttrbrts commented
In theory, Cypress should report the test results as comments in PRs, and the history will be publicly available at https://dashboard.cypress.io/projects/vrh5u7

2021-03-12 13:20 UTC, Cronus1007 commented
@mttrbrts I have a question that the tests should be controlled via the main directory rather than the storybook package.

2021-03-12 13:24 UTC, mttrbrts commented
> @mttrbrts I have a question that the tests should be controlled via the main directory rather than the storybook package. Whats your opinion regarding this?

That's a good question. For these E2E tests, we want to test the components in context (i.e. in an app), and so storybook is a convenient tool for that. I agree that we should be able to run the tests from a `package.json` script at the root-level too (I'll add it to this PR).

Unit tests for example are better suited to being situated local to the module / package that they are testing.

2021-03-12 13:26 UTC, Cronus1007 commented
@mttrbrts For unit tests you can have a link at this comment https://github.com/accordproject/web-components/issues/14#issuecomment-796096658

2021-03-12 13:45 UTC, rkotangoor commented
@sanketshevkar : could you add instructions to storybook Readme on how to run the cypress tests? Pretty much what you have included in this PR description?

2021-03-12 14:01 UTC, sanketshevkar commented
> @sanketshevkar : could you add instructions to storybook Readme on how to run the cypress tests? Pretty much what you have included in this PR description? 

Sure would do that 👍.

2021-03-12 18:06 UTC, sanketshevkar commented
@mttrbrts @rkotangoor I've updated the readme file.

2021-03-13 18:04 UTC, DianaLease commented
> This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/vrh5u7/settings?utm_source=github)

This is awesome. @mttrbrts what kicks off the test run? Whenever a new PR is opened?

2021-03-13 19:11 UTC, mttrbrts commented
> > This comment has been generated by **cypress-bot** as a result of this project's GitHub integration settings. You can manage this integration in [this project's settings in the Cypress Dashboard](https://dashboard.cypress.io/projects/vrh5u7/settings?utm_source=github)
> 
> This is awesome. @mttrbrts what kicks off the test run? Whenever a new PR is opened?

Thanks, yes, here's the config from cypress.io 
![image](https://user-images.githubusercontent.com/7544022/111041415-fabdbc80-842f-11eb-82e0-702e879706d7.png)

2021-03-15 16:52 UTC, Cronus1007 commented
@mttrbrts Shall we update this to Travis CI/CD pipeline plus `codecov` report to the repository whenever a new PR is opened.

2021-03-16 12:45 UTC, irmerk requested changes
Needs investigation by @accordproject/maintainers-ui or @mttrbrts.

2021-03-16 13:21 UTC, mttrbrts commented
> @mttrbrts Shall we update this to Travis CI/CD pipeline plus `codecov` report to the repository whenever a new PR is opened.

This is a separate issue. Let's focus on getting this change in first.

2021-03-16 13:28 UTC, mttrbrts requested changes
@sanketshevkar can you fix `package-lock.json`, please? Otherwise, we're ready to merge this.

2021-03-16 15:22 UTC, sanketshevkar commented
> @sanketshevkar can you fix `package-lock.json`, please? Otherwise, we're ready to merge this.
I'm not able to find where the merge conflict is exactly located. Can someone help me out?

2021-03-16 15:41 UTC, Cronus1007 commented
@sanketshevkar First of all update your branch. This will remove the `merge-conflicts` .

2021-03-16 16:30 UTC, sanketshevkar commented
@mttrbrts why is it expecting a dco of mine from some other id. I've made all my dco sign off's using shevkar.sanket@gmail.com.

2021-03-16 16:32 UTC, mttrbrts commented
> @mttrbrts why is it expecting a dco of mine from some other id. I've made all my dco sign off's using [shevkar.sanket@gmail.com](mailto:shevkar.sanket@gmail.com).

Apologies, I've been trying (and failing!) to fix this properly. I've now manually reviewed and approved the commits.

2021-03-16 16:34 UTC, mttrbrts approved these changes

2021-03-16 16:35 UTC, sanketshevkar commented
@mttrbrts I've updated my branch and created new package-lock.json file. Should I commit that?

2021-03-16 16:37 UTC, sanketshevkar commented
> > @mttrbrts why is it expecting a dco of mine from some other id. I've made all my dco sign off's using [shevkar.sanket@gmail.com](mailto:shevkar.sanket@gmail.com).
> 
> 
> 
> Apologies, I've been trying (and failing!) to fix this properly. I've now manually reviewed and approved the commits. 

No, problem. Thanks a lot for helping out.

2021-03-16 17:13 UTC, irmerk commented
So, as of right now, we manually run this locally and it will produce a test result in Cypress? Next steps will be:
- Set up automatic runs in the Travis (soon to be GitHub Actions) scripts to potentially run in each PR? 
- Continue to iterate on the Cypress test suite?

2021-03-17 08:15 UTC, mttrbrts commented
> So, as of right now, we manually run this locally and it will produce a test result in Cypress? Next steps will be:
> 
> * Set up automatic runs in the Travis (soon to be GitHub Actions) scripts to potentially run in each PR?
> * Continue to iterate on the Cypress test suite?

Yes, that's right. Although the PR integration is already setup (without using Travis or GH Actions). See https://github.com/accordproject/web-components/pull/282#issuecomment-797491849

2021-03-17 11:35 UTC, irmerk approved these changes
👏🏻

2021-03-17 11:45 UTC, merged