cleaned up irrelevant dependencies in ui-markdown-edito
accordproject/web-components pull request #290
Opened 2021-03-11 09:54 UTC by Cronus1007

# Closes #52 

### Changes
- Removed rimraf package
- Removed npm-run-all package

### Flags
- NPM documentation for rimraf https://www.npmjs.com/package/rimraf
- NPM documentation for npm-run-all https://www.npmjs.com/package/npm-run-all

### Screenshots or Video

### Related Issues
- Issue #52 

### Author Checklist
- [x] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [x] Vital features and changes captured in unit and/or integration tests
- [x] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [x] Extend the documentation, if necessary
- [x] Merging to `master` from `fork:branchname`
- [x] Manual accessibility test performed
    - [x] Keyboard-only access, including forms
    - [x] Contrast at least WCAG Level A
    - [x] Appropriate labels, alt text, and instructions

2021-03-15 14:18 UTC, Cronus1007 commented
@irmerk @mttrbrts Any updates?

2021-03-15 14:27 UTC, raghavdhingra commented on packages/ui-markdown-editor/package.json
> -    "rimraf": "3.0.2",
@Cronus1007 Can you please specify the types of check that you've performed

2021-03-15 19:11 UTC, shivaylamba approved these changes

2021-03-16 12:43 UTC, irmerk requested changes
Needs investigation by @accordproject/maintainers-ui

2021-03-23 14:38 UTC, Cronus1007 commented
@irmerk I have rebase the commits. Any updates regarding this PR?

2021-04-02 14:02 UTC, irmerk commented
Looking at this now @Cronus1007 , apologies for the delay. Can you rebase to resolve conflicts in `packages/ui-markdown-editor/package.json`?

2021-04-02 18:23 UTC, Cronus1007 commented
@irmerk I have resolved merge conflicts.

2021-04-06 14:36 UTC, irmerk commented on packages/ui-contract-editor/README.md
> +For more information in realtion to the `props` , `values` and `functionality` of Contract Editor visit [README.md](./src/ContractEditor/README.md)
One last change, I think we should remove this last line since that `README` file no longer exists.

2021-04-06 14:36 UTC, irmerk commented on packages/ui-contract-editor/README.md
> +For more information in realtion to the `props` , `values` and `functionality` of Contract Editor visit [README.md](./src/ContractEditor/README.md)
Also keep the `---` horizontal rule just after this section you added.

2021-04-06 15:47 UTC, irmerk commented
Still unsure about the huge addition to `package-lock` when dependencies are being removed. Please rebase to one commit.

2021-04-06 17:47 UTC, Cronus1007 commented
@irmerk I have updated a little bit of `ui-contract-editor/Readme.md` to resolve the newly linked issue.

2021-05-24 17:19 UTC, closed without merging