feature(build) : Migrate from Travis CI to GitHub actions - 235
accordproject/web-components pull request #316
Opened 2021-03-24 05:02 UTC by rkotangoor

Signed-off-by: Radhika Kotangoor <radhika@clause.io>

### Related Issue
- Issue #235

### Changes

- [ ] Remove .travis.yml and .travis directories in repo
- [ ] Add .github/workflows directory based on those in ./concerto/.github/workflows
- [ ] Remove scripts in ./scripts replace by those found in ./concerto/scripts
- [ ] Fixed package.json by removing the old scripts

### Author Checklist
- [ ] Ensure you provide a [DCO sign-off](https://github.com/probot/dco#how-it-works) for your commits using the `--signoff` option of git commit.
- [ ] Vital features and changes captured in unit and/or integration tests
- [ ] Commits messages follow [AP format](https://github.com/accordproject/techdocs/blob/master/DEVELOPERS.md#commit-message-format)
- [ ] Extend the documentation, if necessary
- [ ] Merging to `master` from `fork:branchname`
- [ ] Manual accessibility test performed
    - [ ] Keyboard-only access, including forms
    - [ ] Contrast at least WCAG Level A
    - [ ] Appropriate labels, alt text, and instructions

2021-03-24 10:30 UTC, mttrbrts commented
Thanks @rkotangoor for your contribution, it appears that the build is failing on the unused `pretest` script in `package.json`. See https://github.com/accordproject/web-components/blob/master/package.json#L38

For now, I suggest removing the `npm run test` step from this GitHub Actions script. We do need to run test automatically on commits, however, let's separate fixing that issue from migrating from Travis.

2021-03-25 23:02 UTC, jeromesimeon requested changes

2021-03-25 23:02 UTC, jeromesimeon commented on .github/workflows/build.yml
> +      - notify
Looks really good @rkotangoor ! This `- notify` dependency will have to be removed since we deleted the `notify` part of the workflow.

2021-03-26 10:52 UTC, rkotangoor commented
@mttrbrts , thank you for opening this [build issue on windows](https://github.com/accordproject/cicero/issues/628). Please suggest on how we want to proceed with this PR while the automated tests on windows issue is resolved.

2021-03-26 14:04 UTC, irmerk commented
Will this close #235?

2021-03-26 14:17 UTC, rkotangoor commented
> Will this close #235?

@irmerk , I believe so

2021-03-26 14:28 UTC, mttrbrts approved these changes

2021-03-26 14:29 UTC, merged